### ISSUE TITLE
Implement Bubble sort in C++

### ISSUE THREAD

**Issue by yasirunilan** [yasirunilan/Algorithms#3]
Implement the Bubble sort in C++ language while following the contributing guideline.

**Comment by yotam180** [comment]
Are you sure this is the goal of Hacktoberfest? :confused:

**Comment by yasirunilan** [comment]
@yotam180 I don't see any problem with this

**Comment by Anirudh257** [comment]
Can I work on this if this is still open?

**Comment by yasirunilan** [comment]
@Anirudh257 yes this is open

**Comment by VibhorCodecianGupta** [comment]
I have a nice code snippet for this algo as well, I would like to contribute

**Comment by yotam180** [comment]
@yasirunilan Of course, yeah, this is allowed. But don't you think that this kind of repositories kinda ruins the act of contribution? Like, instead of actually helping people and making GitHub repositories richer, people go to repositories that say "Hello please pull request here"...

I'm not trying to offend or insult, don't get me wrong. It's just my first time hearing of Hacktoberfest and I really am confused about the idea.

**Comment by yasirunilan** [comment]
@yotam180 To some extent I also agree with you, but I'm also a contributor to several other projects so working with project kind of Repos and these type of Repos are both Open Source Contributions on GitHub. So non taken these kind of repos too exist. It's totally upto the users to select which repos to contribute.

**Comment by yasirunilan** [comment]
@yotam180 and also one of my intention was to provide a support for the developers who are making their first contribution by providing a easy work to start with.
